# Generated by Django 3.1.4 on 2021-01-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='lastbidding_by',
            new_name='lastBid',
        ),
    ]
