# Generated by Django 3.1.4 on 2021-01-10 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210108_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watched',
        ),
        migrations.AddField(
            model_name='listing',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
