# Generated by Django 3.1.4 on 2021-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210117_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lastBid',
        ),
        migrations.AddField(
            model_name='listing',
            name='lastbidding_by',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
